### ISSUE TITLE
closh start failes

### ISSUE THREAD

**Issue by glor** [dundalek/closh#81]
When I start closh, memory and CPU usage go up until all memory is taken and the program crashes
```
$ closh
internal/child_process.js:357
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:357:11)
    at spawn (child_process.js:528:9)
    at Object.<anonymous> (/usr/lib/node_modules/closh/node_modules/lumo-cljs/bin/lumo:16:3)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
```

**Comment by dundalek** [comment]
Hi, what OS are you running?

And what version of node and lumo do you have? You can find out by running `node -v` and `lumo -v`.

**Comment by glor** [comment]
Oh sry. I should have thought about that
```
$ node -v
v10.4.0
```
```
$ lumo -v
Lumo 1.8.0
ClojureScript 1.9.946
Node.js v9.2.0
 Docs: (doc function-name-here)
       (find-doc "part-of-name-here")
 Source: (source function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> 
```
```
$ uname -a
Linux glor-manjaro 4.9.107-2-MANJARO #1 SMP PREEMPT Sat Jun 9 11:12:59 UTC 2018 x86_64 GNU/Linux
```
manjaro is nearly like arch linux

**Comment by dundalek** [comment]
Could you try switching to node v9 and reinstalling closh? A convenient way to switch node versions is [nvm](https://github.com/creationix/nvm).
